Update cmdline options

diff --git a/roll b/roll
--- a/roll
+++ b/roll
@@ -21,17 +21,13 @@ has (){ command -v $1 &> /dev/null; }
 cleanup (){ (( audpid > 1 )) && kill $audpid &>/dev/null; }
 quit (){ echo -e "\x1b[2J \x1b[0H ${purp}<3 \x1b[?25h \x1b[u \x1b[m"; }
 
-# Run quit/cleanup after getting INT/EXIT
-trap 'cleanup' INT
-trap 'quit' EXIT
-
 usage (){
 echo -en "\
 ${green}Rick Astley performs ♪ Never Gonna Give You Up ♪ on STDOUT. $purp[v$version]
 ${yell}Usage: ./roll [OPTIONS...]
 ${purp}OPTIONS: $yell
-  help   - Show this message.
-  inject - Append to $purp$USER$yell's bashrc. (Recommended :D)\
+  help	-h	--help		- Show this message.
+  inject	--inject	- Append to $purp$USER$yell's bashrc. (Recommended :D)
 "
 }
 
@@ -47,10 +43,10 @@ inject (){
 }
 
 case "$@" in
-  help|-h|--h)
+  help|-h|--help)
     usage
     exit;;
-  inject)
+  inject|--inject)
     inject
     exit;;
 esac
@@ -127,6 +123,10 @@ except KeyboardInterrupt:
 EOF
   ) < <(bunzip2 /tmp/roll.bz2 -dc -q 2)
 }
+
+# Run quit/cleanup after getting INT/EXIT
+trap 'cleanup' INT
+trap 'quit' EXIT
 
 get_video
 get_audio
